// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.row({
  address: __t.string().primaryKey(),
  currentStreak: __t.f64().name("current_streak"),
  highestStreak: __t.f64().name("highest_streak"),
  allTimeGmCount: __t.f64().name("all_time_gm_count"),
  lastGmDay: __t.u256().name("last_gm_day"),
  updatedAt: __t.timestamp().name("updated_at"),
});
