// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  address: __t.string(),
  chainId: __t.i32(),
  lastGmDayOnchain: __t.i32(),
  txHash: __t.option(__t.string()),
  fid: __t.option(__t.i64()),
  displayName: __t.option(__t.string()),
  username: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  primaryWallet: __t.option(__t.string()),
};
