// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicType as __AlgebraicTypeType,
  AlgebraicType as __AlgebraicTypeValue,
  type BinaryReader as __BinaryReader,
  type BinaryWriter as __BinaryWriter,
  type Timestamp as __Timestamp,
} from "spacetimedb";

export type GmStatsByAddress = {
  addressChain: string;
  address: string;
  chainId: number;
  currentStreak: number;
  highestStreak: number;
  allTimeGmCount: number;
  lastGmDay: number;
  lastTxHash: string | undefined;
  fid: bigint | undefined;
  displayName: string | undefined;
  username: string | undefined;
  updatedAt: __Timestamp;
};
let _cached_GmStatsByAddress_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const GmStatsByAddress = {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GmStatsByAddress_type_value)
      return _cached_GmStatsByAddress_type_value;
    _cached_GmStatsByAddress_type_value = __AlgebraicTypeValue.Product({
      elements: [],
    });
    _cached_GmStatsByAddress_type_value.value.elements.push(
      { name: "addressChain", algebraicType: __AlgebraicTypeValue.String },
      { name: "address", algebraicType: __AlgebraicTypeValue.String },
      { name: "chainId", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "currentStreak", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "highestStreak", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "allTimeGmCount", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "lastGmDay", algebraicType: __AlgebraicTypeValue.I32 },
      {
        name: "lastTxHash",
        algebraicType: __AlgebraicTypeValue.createOptionType(
          __AlgebraicTypeValue.String
        ),
      },
      {
        name: "fid",
        algebraicType: __AlgebraicTypeValue.createOptionType(
          __AlgebraicTypeValue.I64
        ),
      },
      {
        name: "displayName",
        algebraicType: __AlgebraicTypeValue.createOptionType(
          __AlgebraicTypeValue.String
        ),
      },
      {
        name: "username",
        algebraicType: __AlgebraicTypeValue.createOptionType(
          __AlgebraicTypeValue.String
        ),
      },
      {
        name: "updatedAt",
        algebraicType: __AlgebraicTypeValue.createTimestampType(),
      }
    );
    return _cached_GmStatsByAddress_type_value;
  },

  serialize(writer: __BinaryWriter, value: GmStatsByAddress): void {
    __AlgebraicTypeValue.serializeValue(
      writer,
      GmStatsByAddress.getTypeScriptAlgebraicType(),
      value
    );
  },

  deserialize(reader: __BinaryReader): GmStatsByAddress {
    return __AlgebraicTypeValue.deserializeValue(
      reader,
      GmStatsByAddress.getTypeScriptAlgebraicType()
    );
  },
};

export default GmStatsByAddress;
