// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  deepEqual as __deepEqual,
  type TableCache as __TableCache,
  type TableHandle as __TableHandle,
} from "spacetimedb";

import type { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";
import type { GmStatsByAddress } from "./gm_stats_by_address_type";

declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `gm_stats_by_address`.
 *
 * Obtain a handle from the [`gmStatsByAddress`] property on [`RemoteTables`],
 * like `ctx.db.gmStatsByAddress`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.gmStatsByAddress.on_insert(...)`.
 */
export class GmStatsByAddressTableHandle<TableName extends string>
  implements __TableHandle<TableName>
{
  // phantom type to track the table name
  readonly tableName!: TableName;
  tableCache: __TableCache<GmStatsByAddress>;

  constructor(tableCache: __TableCache<GmStatsByAddress>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<GmStatsByAddress> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `addressChain` unique index on the table `gm_stats_by_address`,
   * which allows point queries on the field of the same name
   * via the [`GmStatsByAddressAddressChainUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gmStatsByAddress.addressChain().find(...)`.
   *
   * Get a handle on the `addressChain` unique index on the table `gm_stats_by_address`.
   */
  addressChain = {
    // Find the subscribed row whose `addressChain` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): GmStatsByAddress | undefined => {
      for (const row of this.tableCache.iter()) {
        if (__deepEqual(row.addressChain, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: GmStatsByAddress) => void) =>
    this.tableCache.onInsert(cb);

  removeOnInsert = (cb: (ctx: EventContext, row: GmStatsByAddress) => void) =>
    this.tableCache.removeOnInsert(cb);

  onDelete = (cb: (ctx: EventContext, row: GmStatsByAddress) => void) =>
    this.tableCache.onDelete(cb);

  removeOnDelete = (cb: (ctx: EventContext, row: GmStatsByAddress) => void) =>
    this.tableCache.removeOnDelete(cb);

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (
      ctx: EventContext,
      oldRow: GmStatsByAddress,
      newRow: GmStatsByAddress
    ) => void
  ) => this.tableCache.onUpdate(cb);

  removeOnUpdate = (
    cb: (
      ctx: EventContext,
      onRow: GmStatsByAddress,
      newRow: GmStatsByAddress
    ) => void
  ) => this.tableCache.removeOnUpdate(cb);
}
