// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("GmStatsByAddressV2", {
  addressChain: __t.string(),
  address: __t.string(),
  chainId: __t.i32(),
  currentStreak: __t.i32(),
  highestStreak: __t.i32(),
  allTimeGmCount: __t.i32(),
  lastGmDay: __t.i32(),
  lastTxHash: __t.option(__t.string()),
  fid: __t.option(__t.i64()),
  displayName: __t.option(__t.string()),
  username: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  primaryWallet: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});


