// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  addressChain: __t.string().primaryKey().name("address_chain"),
  address: __t.string(),
  chainId: __t.i32().name("chain_id"),
  currentStreak: __t.i32().name("current_streak"),
  highestStreak: __t.i32().name("highest_streak"),
  allTimeGmCount: __t.i32().name("all_time_gm_count"),
  lastGmDay: __t.i32().name("last_gm_day"),
  lastTxHash: __t.option(__t.string()).name("last_tx_hash"),
  fid: __t.option(__t.i64()),
  displayName: __t.option(__t.string()).name("display_name"),
  username: __t.option(__t.string()),
  updatedAt: __t.timestamp().name("updated_at"),
});
