// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicType as __AlgebraicTypeType,
  AlgebraicType as __AlgebraicTypeValue,
  type BinaryReader as __BinaryReader,
  type BinaryWriter as __BinaryWriter,
} from "spacetimedb";

export type IdentityConnected = {};
let _cached_IdentityConnected_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const IdentityConnected = {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_IdentityConnected_type_value)
      return _cached_IdentityConnected_type_value;
    _cached_IdentityConnected_type_value = __AlgebraicTypeValue.Product({
      elements: [],
    });
    _cached_IdentityConnected_type_value.value.elements.push();
    return _cached_IdentityConnected_type_value;
  },

  serialize(writer: __BinaryWriter, value: IdentityConnected): void {
    __AlgebraicTypeValue.serializeValue(
      writer,
      IdentityConnected.getTypeScriptAlgebraicType(),
      value
    );
  },

  deserialize(reader: __BinaryReader): IdentityConnected {
    return __AlgebraicTypeValue.deserializeValue(
      reader,
      IdentityConnected.getTypeScriptAlgebraicType()
    );
  },
};

export default IdentityConnected;
