// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.6.0 (commit ).

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  BinaryWriter as __BinaryWriter,
  type CallReducerFlags as __CallReducerFlags,
  type ClientCache as __ClientCache,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all table handle types
import { GmStatsByAddressTableHandle } from "./gm_stats_by_address_table";
// Import and reexport all types
import { GmStatsByAddress } from "./gm_stats_by_address_type";
// Import and reexport all reducer arg types
import { IdentityConnected } from "./identity_connected_reducer";
import { IdentityDisconnected } from "./identity_disconnected_reducer";
import { ReportGm } from "./report_gm_reducer";

export { IdentityConnected };

export { IdentityDisconnected };

export { ReportGm };

export { GmStatsByAddressTableHandle };

export { GmStatsByAddress };

const REMOTE_MODULE = {
  tables: {
    gm_stats_by_address: {
      tableName: "gm_stats_by_address" as const,
      rowType: GmStatsByAddress.getTypeScriptAlgebraicType(),
      primaryKey: "addressChain",
      primaryKeyInfo: {
        colName: "addressChain",
        colType: (
          GmStatsByAddress.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product
        ).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    report_gm: {
      reducerName: "report_gm",
      argsType: ReportGm.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.6.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (
    imp: __DbConnectionImpl,
    event: __Event<Reducer>
  ) => ({
    ...(imp as DbConnection),
    event,
  }),
  dbViewConstructor: (imp: __DbConnectionImpl) => new RemoteTables(imp),
  reducersConstructor: (
    imp: __DbConnectionImpl,
    setReducerFlags: SetReducerFlags
  ) => new RemoteReducers(imp, setReducerFlags),
  setReducerFlagsConstructor: () => new SetReducerFlags(),
};

// A type representing all the possible variants of a reducer.
export type Reducer =
  | never
  | { name: "IdentityConnected"; args: IdentityConnected }
  | { name: "IdentityDisconnected"; args: IdentityDisconnected }
  | { name: "ReportGm"; args: ReportGm };

export class RemoteReducers {
  constructor(
    private connection: __DbConnectionImpl,
    private setCallReducerFlags: SetReducerFlags
  ) {}

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  reportGm(
    address: string,
    chainId: number,
    lastGmDayOnchain: number,
    txHash: string | undefined,
    fid: bigint | undefined,
    displayName: string | undefined,
    username: string | undefined
  ) {
    const __args = {
      address,
      chainId,
      lastGmDayOnchain,
      txHash,
      fid,
      displayName,
      username,
    };
    const __writer = new __BinaryWriter(1024);
    ReportGm.serialize(__writer, __args);
    const __argsBuffer = __writer.getBuffer();
    this.connection.callReducer(
      "report_gm",
      __argsBuffer,
      this.setCallReducerFlags.reportGmFlags
    );
  }

  onReportGm(
    callback: (
      ctx: ReducerEventContext,
      address: string,
      chainId: number,
      lastGmDayOnchain: number,
      txHash: string | undefined,
      fid: bigint | undefined,
      displayName: string | undefined,
      username: string | undefined
    ) => void
  ) {
    this.connection.onReducer("report_gm", callback);
  }

  removeOnReportGm(
    callback: (
      ctx: ReducerEventContext,
      address: string,
      chainId: number,
      lastGmDayOnchain: number,
      txHash: string | undefined,
      fid: bigint | undefined,
      displayName: string | undefined,
      username: string | undefined
    ) => void
  ) {
    this.connection.offReducer("report_gm", callback);
  }
}

export class SetReducerFlags {
  reportGmFlags: __CallReducerFlags = "FullUpdate";
  reportGm(flags: __CallReducerFlags) {
    this.reportGmFlags = flags;
  }
}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get gmStatsByAddress(): GmStatsByAddressTableHandle<"gm_stats_by_address"> {
    // clientCache is a private property
    return new GmStatsByAddressTableHandle(
      (
        this.connection as unknown as { clientCache: __ClientCache }
      ).clientCache.getOrCreateTable<GmStatsByAddress>(
        REMOTE_MODULE.tables.gm_stats_by_address
      )
    );
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags
> {}

export class DbConnection extends __DbConnectionImpl<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags
> {
  static builder = (): __DbConnectionBuilder<
    DbConnection,
    ErrorContext,
    SubscriptionEventContext
  > =>
    new __DbConnectionBuilder<
      DbConnection,
      ErrorContext,
      SubscriptionEventContext
    >(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  subscriptionBuilder = (): SubscriptionBuilder =>
    new SubscriptionBuilder(this);
}

export type EventContext = __EventContextInterface<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags,
  Reducer
>;
export type ReducerEventContext = __ReducerEventContextInterface<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags,
  Reducer
>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags
>;
export type ErrorContext = __ErrorContextInterface<
  RemoteTables,
  RemoteReducers,
  SetReducerFlags
>;
